"module.exports = {"
"  compress: true,"
"  swcMinify: true,"
"  images: {"
"    unoptimized: true,"
"  },"
"  compiler: {"
"    removeConsole: process.env.NODE_ENV === 'production',"
"  },"
"}"
